name: pomodoro_task_timer
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.1
  freezed_annotation: ^2.2.0
  uuid: ^4.1.0
  duration_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
